version: '3.4'

services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ${PWD}/backend
      dockerfile: docker/Dockerfile.development
    environment:
      FLASK_ENV: ${FLASK_ENV}
      FLASK_CONFIG: ${FLASK_CONFIG}
      SECRET_KEY: ${SECRET_KEY}
      APPLICATION_DB: ${APPLICATION_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOSTNAME: "db"
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ${PWD}/backend/:/opt/code
    ports:
      - "5000:5000"

volumes:
  pgdata: