version: '3.4'

services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APPLICATION_DB: ${APPLICATION_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ${PWD}/backend/db/:/docker-entrypoint-initdb.d/

  backend:
    build:
      context: ${PWD}/backend
      dockerfile: docker/Dockerfile.production
    environment:
      FLASK_ENV: ${FLASK_ENV}
      FLASK_CONFIG: ${FLASK_CONFIG}
      SECRET_KEY: ${SECRET_KEY}
      APPLICATION_DB: ${APPLICATION_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOSTNAME: "database"
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ${PWD}/backend/:/opt/code
    depends_on:
      - database

  nginx:
    image: nginx
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  pgdata: